numpy

In [1]:
import numpy as np
arr=np.array([2,5,6,4,3])
print(arr)
print(type(arr))

[2 5 6 4 3]
<class 'numpy.ndarray'>


In [2]:
print(np.__version__)

1.26.4


In [3]:
print(type(arr))

<class 'numpy.ndarray'>


dimensions in array

In [4]:
a=np.array(30)
print(a)

30


In [5]:
#1-d array
a=np.array([3,6,2,1])
print(a)

30


In [ ]:
#2-d array
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
#3-d array
a=np.array([[[1,2,3],[4,5,6]],[[2,4,6],[3,5,6]]])
print(a)

[[[1 2 3]
  [4 5 6]]

 [[2 4 6]
  [3 5 6]]]


In [ ]:
#num of dimension
a=np.array(32)
b=np.array([1,2,3,4])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[2,3,4],[5,6,7]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
#higher dimension
a=np.array([2,4,6,8],ndmin=4)
print(a)
print(a.ndim)


[[[[2 4 6 8]]]]
4


array indexing


In [ ]:
a=np.array([1,2,3,4,5])
print(a[1])

2


In [ ]:
a=np.array([1,2,3,4,5,6])
print(a[4]+a[5])

11


In [ ]:
#access 2d array
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print("3rd element of 2nd row" ,a[1,2])


[[1 2 3 4]
 [5 6 7 8]]
3rd element of 2nd row 7


In [ ]:
#3-d array
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[5,6,8]]])
print(a)
print('3rd element of 3rd row',a[0,1,2])

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [5 6 8]]]
3rd element of 3rd row 6


In [ ]:
#negative indexing
a=np.array([[1,2,3],[4,5,6]])
print(a[1,-1])

6


array slicing

In [8]:
a=np.array([1,2,3,4,5])
print(a[1:3])


[2 3]


In [6]:
a=np.array([1,2,3,4,5])
print(a[:4])

[1 2 3 4]


In [7]:
a=np.array([1,2,3,4,5])
print(a[2:])

[3 4 5]


In [ ]:
a=np.array([1,2,3,4,5])
print(a[-4:-1])

[2 3 4]


In [ ]:
#step
a=np.array([1,2,3,4,5])
print(a[1:4:2])

[2 4]


In [ ]:
a=np.array([1,2,3,4,5])
print(a[::4])

[1 5]


In [ ]:
#slicing 2d array
a=np.array([[1,2,3],[4,5,6]])
print(a[1,2:4])

[6]


In [ ]:
#slicing 2d array
a=np.array([[1,2,3],[4,5,6]])
print(a[1:2,2])

[6]


In [ ]:
a=np.array([[1,2,3],[4,5,6]])
print(a[0:2,1:4])

[[2 3]
 [5 6]]


numpy datatypes

In [ ]:
a=np.array([1,2,3,4,5])
print(a.dtype)

int64


In [ ]:
a=np.array(['abc','pqr','xyz'])
print(a.dtype)

<U3


In [ ]:
a=np.array([2,3,4,5],dtype='S')
print(a)
print(a.dtype)

[b'2' b'3' b'4' b'5']
|S1


In [ ]:
a=np.array([1,2,3,4],dtype='i4')
print(a)
print(a.dtype)

[1 2 3 4]
int32


In [ ]:
#conerting datatypes in extisting array
a=np.array([1,2,3,4,5,6])
b=a.astype('f')
print(b)
print(b.dtype)

[1. 2. 3. 4. 5. 6.]
float32


In [ ]:
a=np.array([1.4,2.3,3.6,4.5,5.7,6])
b=a.astype('int')
print(b)
print(b.dtype)

[1 2 3 4 5 6]
int64


In [ ]:
a=np.array([1,2,3,0,4,5,6])
b=a.astype('bool')
print(b)
print(b.dtype)

[ True  True  True False  True  True  True]
bool


copy vs. view

In [ ]:
a=np.array([1,2,3,4])
b=a.copy()
a[1]=23
print(a)
print(b)

[ 1 23  3  4]
[1 2 3 4]


In [ ]:
a=np.array([1,2,3,4])
b=a.view()
a[1]=23
print(a)
print(b)

[ 1 23  3  4]
[ 1 23  3  4]


In [ ]:
a=np.array([1,2,3,4])
b=a.copy()
c=a.view()

print(a.base)
print(b.base)
print(c.base)

None
None
[1 2 3 4]


array shape

In [ ]:
a =np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [ ]:
a =np.array([[1,2,3],[4,5,6]],ndmin=3)
print(a.shape)

(1, 2, 3)


array reshape

In [ ]:
a=np.array([1,2,3,4,5,6,7,8])
b=a.reshape(2,4)
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
#1d to 3d
a =np.array([1,2,3,4,5,6,7,8])
b=a.reshape(2,2,2)
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
a =np.array([1,2,3,4,5,6,7,8])
print(a.reshape(2,4).base)

[1 2 3 4 5 6 7 8]


In [ ]:
a =np.array([1,2,3,4,5,6,7,8])
b=a.reshape(2,2,-1)
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


flattening arrays

In [ ]:
a =np.array([[1,2,3,4],[5,6,7,8]])
b=a.reshape(-1)
print(b)

[1 2 3 4 5 6 7 8]


array iterating

In [ ]:
a=np.array([1,3,5,7])
for x in a:
  print(x)

1
3
5
7


In [ ]:
#2-d array
a=np.array([[1,2,3],[4,5,6]])
for x in a:
  for y in x:
    print(y)

1
2
3
4
5
6


In [ ]:
#3d array
a =np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,4,7]]])
for x in a:
  print(a)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 4 7]]]
[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 4 7]]]


In [ ]:
a =np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,4,7]]])
for x in a:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
1
4
7


In [ ]:
#nditer
a =np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,4,7]]])
for x in np.nditer(a):
  print(x)


1
2
3
4
5
6
7
8
9
1
4
7


In [ ]:
a=np.array([1,2,3])
for x in np.nditer(a,flags=['buffered'],op_dtypes=['S']):
  print(x)


b'1'
b'2'
b'3'


In [ ]:
#iterating with diff stepsixe
a=np.array([[1,2,3],[4,5,6]])
for x in np.nditer(a[:,::2]):
  print(x)

1
3
4
6


array join

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.concatenate((a,b))
print(c)

[1 2 3 4 5 6]


In [ ]:
#join 2d array
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[3,6,9]])
c=np.concatenate((a,b),axis=1)
print(c)

[[1 2 3 7 8 9]
 [4 5 6 3 6 9]]


In [ ]:
#join using stack fun
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[3,6,9]])
c=np.stack((a,b),axis=1)
print(c)

[[[1 2 3]
  [7 8 9]]

 [[4 5 6]
  [3 6 9]]]


In [ ]:
#stacking along rows hstack()
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[3,6,9]])
c=np.hstack((a,b))
print(c)


[[1 2 3 7 8 9]
 [4 5 6 3 6 9]]


In [ ]:
#stacking along rows vstack
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[3,6,9]])
c=np.vstack((a,b))
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [3 6 9]]


In [ ]:
#stacking along height(depth)
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[3,6,9]])
c=np.dstack((a,b))
print(c)

[[[1 7]
  [2 8]
  [3 9]]

 [[4 3]
  [5 6]
  [6 9]]]


array split

In [ ]:
a=np.array([1,2,3,4,5,6])
b=np.array_split(a,3)
print(b)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
#split into array
a=np.array([1,2,3,4,5,6])
b=np.array_split(a,3)
print(b[0])
print(b[1])
print(b[2])

[1 2]
[3 4]
[5 6]


In [ ]:
#splitting 2d array
a=np.array([[1,2,3],[4,5,6]])
b=np.array_split(a,3)
print(b)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int64)]


In [ ]:
#
a=np.array([[1,2,3],[4,5,6]])
b=np.array_split(a,3,axis=1)
print(b)

[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [ ]:
#hsplit alternate of hstack()
a=np.array([[1,2,3],[4,5,6]])
b=np.array_split(a,3)
print(b)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int64)]


array search

In [ ]:
a=np.array([1,2,3,4,5,3])
b=np.where(a==3)
print(b)

(array([2, 5]),)


In [ ]:
a=np.array([1,2,3,4,5,3])
b=np.where(a%2==0)
print(b)

(array([1, 3]),)


search sorted

In [ ]:
a=np.array([1,2,3,4,5,3])
b=np.searchsorted(a,4)
print(b)

3


In [ ]:
a=np.array([1,2,3,4,5,3])
b=np.searchsorted(a,4,side='right')
print(b)

6


In [ ]:
#multiple values
a=np.array([1,2,3,4,5,3])
b=np.searchsorted(a,[4,2])
print(b)

[3 1]


sort array

In [ ]:
a=np.array([1,2,3,4,5,3])
print(np.sort(a))

[1 2 3 3 4 5]


In [ ]:
arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [ ]:
a= np.array(['True','False','True'])
print(np.sort(a))

['False' 'True' 'True']


In [ ]:
#sorting 2d array
a=np.array([[1,2,3],[4,1,2]])
b=np.sort(a)
print(b)

[[1 2 3]
 [1 2 4]]


array filter

In [12]:
b=np.array([3,1,4])
x=np.array([True,False,True])
c = b[x]
print(c)

[3 4]


filter array

In [ ]:
a=np.array([1,4,6,8,3])
filter_array=[]
for ele in a:
  if ele > 4:
    filter_array.append(True)
  else:
    filter_array.append(False)
b=a[filter_array]
print(filter_array)
print(b)


[False, False, True, True, False]
[6 8]


In [ ]:
#creating filter dirctly
a=np.array([1,4,6,8,3])
f_a= a>4
b=a[f_a]
print(f_a)
print(b)

[False False  True  True False]
[6 8]
