In [1]:
import numpy as np
def add1(x,y):
  return x+y
add1=np.frompyfunc(add1,2,1)
print(add1([2,4,6,8],[1,3,5,7]))



[3 7 11 15]


In [2]:
print(type(np.add))

<class 'numpy.ufunc'>


In [3]:
if type(np.add)==np.ufunc:
    print('it is ufunc')
else:
    print('it is not unfc')


it is ufunc


In [4]:
a=np.array([1,2,3,4,5])
b=np.array([2,4,6,8,4])

In [5]:
c=np.add(a,b)
print(c)


[ 3  6  9 12  9]


In [6]:
c=np.subtract(a,b)
print(c)

[-1 -2 -3 -4  1]


In [7]:
c=np.multiply(a,b)
print(c)

[ 2  8 18 32 20]


In [8]:
c=np.divide(a,b)
print(c)

[0.5  0.5  0.5  0.5  1.25]


In [9]:
c=np.power(a,b)
print(c)

[    1    16   729 65536   625]


In [10]:
c=np.mod(a,b)
print(c)

[1 2 3 4 1]


In [11]:
c=np.divmod(a,b)
print(c)

(array([0, 0, 0, 0, 1]), array([1, 2, 3, 4, 1]))


In [12]:
c=np.absolute(a,b)
print(c)

[1 2 3 4 5]
